BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS DOCTORES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL,
  especialidad TEXT,
  disponible INTEGER NOT NULL DEFAULT 1 -- 1=libre,0=ocupado
);

CREATE TABLE IF NOT EXISTS TRABAJADORES_SOCIALES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL,
  edad INTEGER,
  sexo TEXT
);

CREATE TABLE IF NOT EXISTS CAMAS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  codigo TEXT NOT NULL UNIQUE,
  disponible INTEGER NOT NULL DEFAULT 1 -- 1=libre,0=ocupada
);

CREATE TABLE IF NOT EXISTS VISITAS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  folio TEXT UNIQUE, -- generado: IDPACIENTE+IDDOCTOR+SALA+CONSECUTIVO
  paciente_id INTEGER NOT NULL,
  doctor_id INTEGER,
  cama_id INTEGER,
  sala TEXT NOT NULL, -- nombre/ID de la sala que creó la visita
  trabajador_social_id INTEGER,
  estado TEXT NOT NULL DEFAULT 'ABIERTA', -- ABIERTA / CERRADA / ASIGNADA
  creado_en DATETIME DEFAULT CURRENT_TIMESTAMP,
  cerrado_en DATETIME,
  consecutivo INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (paciente_id) REFERENCES PACIENTES(id),
  FOREIGN KEY (doctor_id) REFERENCES DOCTORES(id),
  FOREIGN KEY (cama_id) REFERENCES CAMAS(id),
  FOREIGN KEY (trabajador_social_id) REFERENCES TRABAJADORES_SOCIALES(id)
);

CREATE TABLE IF NOT EXISTS WAL_LOG (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  op TEXT NOT NULL, -- JSON string de la operación (insert/update)
  creado_en DATETIME DEFAULT CURRENT_TIMESTAMP,
  applied INTEGER DEFAULT 0 -- 0=pendiente,1=aplicado
);

COMMIT;
