PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS DOCTORES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL,
  especialidad TEXT,
  disponible INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS TRABAJADORES_SOCIALES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTES (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  nombre TEXT NOT NULL,
  edad INTEGER,
  sexo TEXT
);

CREATE TABLE IF NOT EXISTS CAMAS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  codigo TEXT NOT NULL,
  disponible INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS VISITAS (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  paciente_id INTEGER NOT NULL,
  trabajador_social_id INTEGER NOT NULL,
  doctor_id INTEGER,
  cama_id INTEGER,
  sala TEXT NOT NULL,
  folio TEXT,
  estado TEXT NOT NULL DEFAULT 'ABIERTA',
  consecutivo INTEGER NOT NULL DEFAULT 0,
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cerrado_en DATETIME,
  FOREIGN KEY (paciente_id) REFERENCES PACIENTES(id),
  FOREIGN KEY (trabajador_social_id) REFERENCES TRABAJADORES_SOCIALES(id),
  FOREIGN KEY (doctor_id) REFERENCES DOCTORES(id),
  FOREIGN KEY (cama_id) REFERENCES CAMAS(id)
);

CREATE TABLE IF NOT EXISTS WAL_LOG (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  op_type TEXT NOT NULL,
  payload TEXT NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
